# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MNfIob-haYF-G8qRum6IjCYZoCFvaEV7
"""

import streamlit as st
import pandas as pd
import numpy as np
import io
import locale
import altair as alt
from datetime import datetime

try:
    locale.setlocale(locale.LC_TIME, 'fr_FR.UTF-8')
except:
    try:
        locale.setlocale(locale.LC_TIME, 'fr_FR')
    except:
        pass

st.set_page_config(page_title="Dashboard KPIS MC et FEED", layout="wide")

import streamlit as st
import random
import time

import streamlit as st
import random
import time

# ==================================================
# HSE - CONSIGNE DE SECURITE
# ==================================================

consignes = [
    "Port obligatoire des EPI avant toute intervention.",
    "Port obligatoire du casque de sécurité.",
    "Port obligatoire des lunettes de protection.",
    "Port obligatoire des gants adaptés au travail.",
    "Utiliser les protections auditives dans les zones bruyantes.",
    "Vérifier l'absence de tension avant toute intervention électrique.",
    "Respecter la procédure de consignation et déconsignation.",
    "Ne jamais intervenir sur un équipement en marche.",
    "Baliser et sécuriser la zone de travail.",
    "Maintenir le poste de travail propre et ordonné.",
    "Vérifier l'état des outils avant utilisation.",
    "Utiliser uniquement du matériel homologué.",
    "Respecter les permis de travail en vigueur.",
    "Identifier les risques avant de commencer une tâche.",
    "Signaler immédiatement toute situation dangereuse.",
    "Signaler tout incident ou presque accident.",
    "Ne jamais neutraliser un dispositif de sécurité.",
    "Vérifier les détecteurs de gaz avant utilisation.",
    "Vérifier la bonne ventilation des zones de travail.",
    "Respecter les règles des espaces confinés.",
    "Contrôler l'atmosphère avant d'entrer dans un espace confiné.",
    "Utiliser les points d'ancrage pour les travaux en hauteur.",
    "Vérifier l'état des échafaudages avant utilisation.",
    "Sécuriser les outils lors des travaux en hauteur.",
    "Ne pas travailler seul lors d'opérations à risque.",
    "Contrôler les élingues avant chaque levage.",
    "Respecter les limites de charge des équipements.",
    "Vérifier l'état des appareils de levage.",
    "Maintenir les voies de circulation dégagées.",
    "Respecter la signalisation de sécurité.",
    "Vérifier les extincteurs à proximité du chantier.",
    "Connaître les issues de secours les plus proches.",
    "Respecter les procédures d'arrêt d'urgence.",
    "Vérifier les flexibles et raccords avant mise en service.",
    "Contrôler les fuites avant démarrage d'un équipement.",
    "Respecter les distances de sécurité.",
    "Ne jamais contourner une procédure HSE.",
    "Porter les EPI adaptés au risque identifié.",
    "Prévenir son responsable avant toute intervention particulière.",
    "Analyser les risques avant chaque démarrage de chantier.",
    "Vérifier la stabilité des équipements.",
    "Utiliser les bons outils pour la bonne tâche.",
    "Respecter les consignes spécifiques du chantier.",
    "Ne jamais prendre de raccourci au détriment de la sécurité.",
    "Arrêter immédiatement les travaux en cas de danger.",
    "Protéger l'environnement lors des interventions.",
    "Collecter et trier correctement les déchets.",
    "Éviter toute pollution accidentelle.",
    "Respecter les consignes de stockage des produits dangereux.",
    "Lire les fiches de sécurité avant manipulation.",
    "Vérifier les équipements avant chaque prise de poste.",
    "S'assurer de la disponibilité des moyens de secours.",
    "Communiquer clairement avec l'équipe avant intervention.",
    "Respecter les règles de circulation des engins.",
    "Garder une vigilance permanente sur son environnement.",
    "Prendre le temps d'effectuer le travail en sécurité.",
    "La sécurité est l'affaire de tous.",
    "Chaque incident peut être évité par la prévention.",
    "Aucun travail n'est plus urgent que la sécurité.",
    "Zéro accident commence par un comportement sûr."
]

if "hse_affiche" not in st.session_state:
    st.session_state.hse_affiche = False

if not st.session_state.hse_affiche:

    consigne = random.choice(consignes)

    st.markdown("""
    <h1 style='text-align:center;font-size:55px;'>
        🦺 HSE - CONSIGNE DE SÉCURITÉ
    </h1>
    """, unsafe_allow_html=True)

    st.markdown("""
    <h3 style='text-align:center;color:gray;'>
        Sécurité • Santé • Environnement
    </h3>
    """, unsafe_allow_html=True)

    st.markdown(
        f"""
        <div style="
            background-color:#fff3cd;
            border-left:10px solid #ffc107;
            padding:30px;
            border-radius:15px;
            font-size:34px;
            font-weight:bold;
            text-align:center;
            margin-top:25px;
            margin-bottom:25px;
        ">
            ⚠️ {consigne}
        </div>
        """,
        unsafe_allow_html=True
    )
st.markdown("""
<div style="
    text-align:center;
    font-size:32px;
    font-weight:bold;
    color:#198754;
    margin-top:20px;
    margin-bottom:20px;
">
    Aucun travail n'est plus urgent que la sécurité
</div>
""", unsafe_allow_html=True)

    with st.spinner("Chargement du tableau de bord..."):
        time.sleep(8)

    st.session_state.hse_affiche = True
    st.rerun()

    st.stop()

st.markdown("# KPI Dashboard MC et FEED")

def rename_safe(df, old_names, new_names):
    mapping = {old: new for old, new in zip(old_names, new_names) if old in df.columns}
    return df.rename(columns=mapping)

def contient_mot(texte, liste_mots):
    texte = str(texte)
    return any(mot in texte for liste_mots_element in liste_mots for mot in liste_mots_element.split())

def categorie_age(age):
    if age <= 1: return "<1 mois"
    elif age >= 3: return ">3 mois"
    else: return "1 mois < <3 mois"

def calcul_kpi(numerateur, denominateur, si_zero=100):
    return np.where(denominateur == 0, si_zero, (numerateur / denominateur) * 100)

def creer_pivot(dataframe, filtre, colonne, postes_to_reindex):
    pivot = pd.pivot_table(dataframe[filtre], index="Poste travail princ.", columns=colonne, values="Ordre", aggfunc="count", fill_value=0)
    return pivot.reindex(postes_to_reindex, fill_value=0)

def calculate_all_kpis_and_intermediate_dfs(df_input, avis_df_input, now_timestamp, all_postes_list):
    results = {}
    df_temp = df_input.copy()
    avis_df_temp = avis_df_input.copy()

    mots_prep = ["CRPR ATPD", "CRPR ATMR", "CRPR ATER", "CRPR ATRS", "CRPR ATMO", "ATPD", "ATMR", "ATER", "ATRS", "ATMO"]
    df_temp["Backlog préparation"] = np.where(df_temp["Statut utilisateur"].apply(lambda x: contient_mot(x, mots_prep)), "CARACTERISE", "NON CARACTERISE")
    mots_planif = ["ATPL ATEI", "ATPL ATAL", "ATPL ATER", "ATPL AGAR", "ATPL ATHS", "ATEI", "ATAL", "ATAS", "AGAR", "ATHS"]
    df_temp["Backlog planification"] = np.where(df_temp["Statut utilisateur"].apply(lambda x: contient_mot(x, mots_planif)), "CARACTERISE", "NON CARACTERISE")

    for date_col, age_mois_col, age_col in [('Créé le', "Age mois préparation", "Age préparation"), ('Date de début planifiée', "Age mois planification", "Age planification"), ('Date de début planifiée', "Age mois exécution", "Age exécution")]:
        if date_col in df_temp.columns:
            df_temp[date_col] = pd.to_datetime(df_temp[date_col], errors='coerce')
            df_temp[age_mois_col] = ((now_timestamp.year - df_temp[date_col].dt.year) * 12 + (now_timestamp.month - df_temp[date_col].dt.month)).round(2)
            df_temp[age_col] = df_temp[age_mois_col].apply(categorie_age)
        else:
            df_temp[age_mois_col] = np.nan
            df_temp[age_col] = "Inconnu"

    df_temp["OT CONFIME"] = np.where(df_temp["Statut système"].str.contains("CLO", na=False) & df_temp["Statut système"].str.contains("CONF", na=False), "OUI", "NON")
    df_temp["Contient SOPL"] = df_temp["Statut utilisateur"].str.contains("SOPL", na=False).map({True: 1, False: 0})
    df_temp["OT LANC ESTIME"] = np.where(df_temp["Total coûts budgétés"].fillna(0) == 0, "NON", "OUI")
    df_temp["OT_COR_EGAL"] = np.where((df_temp["Total coûts budgétés"].fillna(0) - df_temp["Total coûts réels"].fillna(0)) == 0, "OUI", "NON")
    results['df_processed'] = df_temp

    analyse = creer_pivot(df_temp, df_temp["Nº appel pl.entret."].fillna(0) == 0, "Statut OT", all_postes_list)
    for col in ["CLOT", "CRÉÉ", "LANC", "TCLO"]: analyse[col] = analyse.get(col, 0)
    analyse["Total"] = analyse[["CLOT", "CRÉÉ", "LANC", "TCLO"]].sum(axis=1)
    analyse["TAUX_REALISATION_CORRECTIF/PT"] = calcul_kpi(analyse["TCLO"], analyse["Total"])

    prep = creer_pivot(df_temp, df_temp["Statut OT"] == "CRÉÉ", "Age préparation", all_postes_list)
    for col in ["<1 mois", ">3 mois", "1 mois < <3 mois"]: prep[col] = prep.get(col, 0)
    prep["Total"] = prep[["<1 mois", "1 mois < <3 mois", ">3 mois"]].sum(axis=1)
    prep["OT préparation <1 mois"] = calcul_kpi(prep["<1 mois"], prep["Total"])
    prep["OT préparation >3 mois"] = calcul_kpi(prep[">3 mois"], prep["Total"], 0)
    prep["OT préparation 1mois< <3mois"] = calcul_kpi(prep["1 mois < <3 mois"], prep["Total"], 0)

    planif = creer_pivot(df_temp, (df_temp["Statut OT"] == "LANC") & (df_temp["Contient SOPL"] == 0), "Age planification", all_postes_list)
    for col in ["<1 mois", ">3 mois", "1 mois < <3 mois"]: planif[col] = planif.get(col, 0)
    planif["Total"] = planif[["<1 mois", "1 mois < <3 mois", ">3 mois"]].sum(axis=1)
    planif["OT planification <1 mois"] = calcul_kpi(planif["<1 mois"], planif["Total"])
    planif["OT planification >3 mois"] = calcul_kpi(planif[">3 mois"], planif["Total"], 0)
    planif["OT planification 1mois< <3mois"] = calcul_kpi(planif["1 mois < <3 mois"], planif["Total"], 0)

    execu = creer_pivot(df_temp, (df_temp["Statut OT"] == "LANC") & (df_temp["Contient SOPL"] == 1), "Age exécution", all_postes_list)
    for col in ["<1 mois", ">3 mois", "1 mois < <3 mois"]: execu[col] = execu.get(col, 0)
    execu["Total"] = execu[["<1 mois", "1 mois < <3 mois", ">3 mois"]].sum(axis=1)
    execu["OT exécution <1 mois"] = calcul_kpi(execu["<1 mois"], execu["Total"])
    execu["OT exécution >3 mois"] = calcul_kpi(execu[">3 mois"], execu["Total"], 0)
    execu["OT exécution 1mois< <3mois"] = calcul_kpi(execu["1 mois < <3 mois"], execu["Total"], 0)

    lanc = pd.pivot_table(df_temp[df_temp["Statut OT"] == "LANC"], index="Poste travail princ.", columns="OT LANC ESTIME", values="Ordre", aggfunc="count", fill_value=0).reindex(all_postes_list, fill_value=0)
    for col in ["OUI", "NON"]: lanc[col] = lanc.get(col, 0)
    lanc["Total"] = lanc["OUI"] + lanc["NON"]
    lanc["OT LANC ESTIME"] = calcul_kpi(lanc["OUI"], lanc["Total"])

    prep_carac = pd.pivot_table(df_temp[df_temp["Statut OT"] == "CRÉÉ"], index="Poste travail princ.", columns="Backlog préparation", values="Ordre", aggfunc="count", fill_value=0).reindex(all_postes_list, fill_value=0)
    for col in ["CARACTERISE", "NON CARACTERISE"]: prep_carac[col] = prep_carac.get(col, 0)
    prep_carac["Total"] = prep_carac["CARACTERISE"] + prep_carac["NON CARACTERISE"]
    prep_carac["Backlog préparation caractérisé"] = calcul_kpi(prep_carac["CARACTERISE"], prep_carac["Total"])

    planif_carac = pd.pivot_table(df_temp[df_temp["Statut OT"] == "LANC"], index="Poste travail princ.", columns="Backlog planification", values="Ordre", aggfunc="count", fill_value=0).reindex(all_postes_list, fill_value=0)
    for col in ["CARACTERISE", "NON CARACTERISE"]: planif_carac[col] = planif_carac.get(col, 0)
    planif_carac["Total"] = planif_carac["CARACTERISE"] + planif_carac["NON CARACTERISE"]
    planif_carac["Backlog planification caractérisé"] = calcul_kpi(planif_carac["CARACTERISE"], planif_carac["Total"])

    for kpi_name, col_name in [("OT CONFIME", "OT CONFIME"), ("OT_COR_EGAL", "OT_COR_EGAL")]:
        df_pivot = pd.pivot_table(df_temp, index="Poste travail princ.", columns=col_name, values="Ordre", aggfunc="count", fill_value=0).reindex(all_postes_list, fill_value=0)
        for c in ["OUI", "NON"]: df_pivot[c] = df_pivot.get(c, 0)
        df_pivot["Total"] = df_pivot["OUI"] + df_pivot["NON"]
        df_pivot[col_name] = calcul_kpi(df_pivot["OUI"], df_pivot["Total"])
        results[kpi_name.lower().replace(" ", "_")] = df_pivot

    avis_df_filtered_local = avis_df_temp[(avis_df_temp["Ordre"].isna()) | (avis_df_temp["Ordre"].astype(str).str.strip() == "")].copy()
    results['avis_df_filtered'] = avis_df_filtered_local

    tableau_croise_avis = pd.pivot_table(avis_df_filtered_local, index="Poste travail princ.", columns="Statut utilisateur", values="Avis", aggfunc="count", fill_value=0).reindex(all_postes_list, fill_value=0)
    for col in ["APRQ", "APRV", "APRV AVAU", "REJT"]: tableau_croise_avis[col] = tableau_croise_avis.get(col, 0)
    tableau_croise_avis["Total"] = tableau_croise_avis[["APRQ", "APRV", "APRV AVAU", "REJT"]].sum(axis=1)
    tableau_croise_avis["appel avis approuvé"] = calcul_kpi(tableau_croise_avis["APRV"], tableau_croise_avis["Total"])

    calculated_kpis_df = pd.concat([
        analyse[["TAUX_REALISATION_CORRECTIF/PT"]], prep[["OT préparation <1 mois", "OT préparation >3 mois", "OT préparation 1mois< <3mois"]],
        planif[["OT planification <1 mois", "OT planification >3 mois", "OT planification 1mois< <3mois"]], execu[["OT exécution <1 mois", "OT exécution >3 mois", "OT exécution 1mois< <3mois"]],
        tableau_croise_avis[["appel avis approuvé"]], lanc[["OT LANC ESTIME"]], prep_carac[["Backlog préparation caractérisé"]],
        planif_carac[["Backlog planification caractérisé"]], results['ot_confime'][["OT CONFIME"]], results['ot_cor_egal'][["OT_COR_EGAL"]]
    ], axis=1)

    results['calculated_kpis_df'] = calculated_kpis_df
    return results

def highlight_kpis(row):
    styles = []
    if row.name == 'CIBLE': return ['padding: 8px; background-color: #d6eaf8; color: #1a5276; font-weight: bold;'] * len(row)
    for col in row.index:
        current_style = 'padding: 8px;'
        try: value = float(row[col])
        except (ValueError, TypeError): styles.append(current_style); continue
        if col in ["OT préparation <1 mois", "OT planification <1 mois", "OT exécution <1 mois"]:
            if value >= 80: current_style += 'background-color:#c6efce; color:#006100;'
            elif value >= 75: current_style += 'background-color:#ffeb9c; color:#9c6500;'
            else: current_style += 'background-color:#ffc7ce; color:#9c0006;'
        elif col in ["OT préparation 1mois< <3mois", "OT planification 1mois< <3mois", "OT exécution 1mois< <3mois"]:
            if value <= 15: current_style += 'background-color:#c6efce; color:#006100;'
            else: current_style += 'background-color:#ffc7ce; color:#9c0006;'
        elif col in ["OT préparation >3 mois", "OT planification >3 mois", "OT exécution >3 mois"]:
            if value <= 5: current_style += 'background-color:#c6efce; color:#006100;'
            else: current_style += 'background-color:#ffc7ce; color:#9c0006;'
        elif col == "TAUX_REALISATION_CORRECTIF/PT":
            if value >= 85: current_style += 'background-color:#c6efce; color:#006100;'
            elif value >= 80: current_style += 'background-color:#ffeb9c; color:#9c6500;'
            else: current_style += 'background-color:#ffc7ce; color:#9c0006;'
        elif col == "appel avis approuvé":
            if value >= 95: current_style += 'background-color:#c6efce; color:#006100;'
            elif value >= 90: current_style += 'background-color:#ffeb9c; color:#9c6500;'
            else: current_style += 'background-color:#ffc7ce; color:#9c0006;'
        elif col in ["OT LANC ESTIME", "Backlog préparation caractérisé", "Backlog planification caractérisé", "OT CONFIME", "OT_COR_EGAL"]:
            if value >= 100: current_style += 'background-color:#c6efce; color:#006100;'
            elif value >= 95: current_style += 'background-color:#ffeb9c; color:#9c6500;'
            else: current_style += 'background-color:#ffc7ce; color:#9c0006;'
        styles.append(current_style)
    return styles

def highlight_classification_table_kpis(row):
    styles = [''] * len(row)
    for i, col in enumerate(row.index):
        if col in ["Score KPIs Quantité", "Score KPIs Qualité", "Total performance "]:
            try:
                s = str(row[col]); value = float(s.replace(' %', '').strip()) if ' %' in s else float(s)
                if value >= 90: styles[i] = 'background-color: #c6efce; color: #006100;'
                elif value >= 80: styles[i] = 'background-color: #ffeb9c; color: #9c6500;'
                else: styles[i] = 'background-color: #ffc7ce; color: #9c0006;'
            except (ValueError, TypeError): pass
    return styles

def get_kpi_score(kpi_name, actual_value, target_value):
    if pd.isna(actual_value) or pd.isna(target_value): return 0
    if kpi_name in ["OT préparation <1 mois", "OT planification <1 mois", "OT exécution <1 mois"]: return 1 if actual_value >= 75 else 0
    if kpi_name in ["OT préparation 1mois< <3mois", "OT planification 1mois< <3mois", "OT exécution 1mois< <3mois"]: return 1 if actual_value <= 15 else 0
    if kpi_name in ["OT préparation >3 mois", "OT planification >3 mois", "OT exécution >3 mois"]: return 1 if actual_value <= 5 else 0
    if kpi_name == "TAUX_REALISATION_CORRECTIF/PT": return 1 if actual_value >= 80 else 0
    if kpi_name == "appel avis approuvé": return 1 if actual_value >= 90 else 0
    if kpi_name in ["OT LANC ESTIME", "Backlog préparation caractérisé", "Backlog planification caractérisé", "OT CONFIME", "OT_COR_EGAL"]: return 1 if actual_value >= 95 else 0
    return 0

def get_groupe_metier(poste):
    p = str(poste).upper()
    if "E" in p: return "Électrique"
    elif "M" in p: return "Mécanique"
    elif "R" in p: return "Instrumentation"
    elif "G" in p: return "Génie Civil"
    return "Autre"

def get_groupe_atelier(poste):
    p = str(poste).upper()
    if "PS" in p: return "Sulfurique"
    elif "PP" in p: return "Phosphorique"
    elif "TSP" in p or "REX" in p: return "Engrais"
    elif "MCP" in p or "DCP" in p: return "Feed"
    return "Autre"

def get_groupe_division(poste):
    p = str(poste).upper()
    if "SF1" in p: return "SF1"
    elif "SF2" in p: return "SF2"
    return "Autre"

use_new_files = st.toggle("Charger de nouveaux fichiers OT et AVIS", value=False)

ot_file = None
avis_file = None

if use_new_files:
    col1, col2 = st.columns(2)
    with col1: ot_file = st.file_uploader("📂 Charger le fichier OT", type=["xlsx"])
    with col2: avis_file = st.file_uploader("📂 Charger le fichier AVIS", type=["xlsx"])
else:
    st.info("💡 Utilisation des données par défaut (ot.xlsx et avis.xlsx dans le répertoire).")

if not use_new_files or (ot_file is not None and avis_file is not None):
    try:
        if use_new_files:
            df_ot_raw = pd.read_excel(ot_file)
            avis_df_raw = pd.read_excel(avis_file)
        else:
            df_ot_raw = pd.read_excel("ot.xlsx")
            avis_df_raw = pd.read_excel("avis.xlsx")

        for col in ["Créé le", "Date de début planifiée", "Date de clôture", "Début réel", "Fin réelle"]:
            if col in df_ot_raw.columns: df_ot_raw[col] = pd.to_datetime(df_ot_raw[col], errors="coerce")
        for col in ["Créé le", "Début souhaité", "Date de la clôture"]:
            if col in avis_df_raw.columns: avis_df_raw[col] = pd.to_datetime(avis_df_raw[col], errors="coerce")

        df_ot_raw_no_cresseur = df_ot_raw[~df_ot_raw["Poste travail princ."].astype(str).str.contains("cresseur", case=False, na=False)]
        all_postes_master_list = sorted(df_ot_raw_no_cresseur[df_ot_raw_no_cresseur["Poste travail princ."].astype(str).str.startswith(("SF1", "SF2"), na=False)]["Poste travail princ."].dropna().unique().tolist())

        col_f1, col_f2, col_f3 = st.columns(3)
        with col_f1:
            selected_postes = st.multiselect("Poste de travail", ["All"] + all_postes_master_list, ["All"])
            if "All" in selected_postes or len(selected_postes) == 0: selected_postes = all_postes_master_list
        with col_f2:
            ateliers_options = ["All", "Sulfurique (PS)", "Phosphorique (PP)", "Engrais (TSP/REX)", "Feed (MCP/DCP)"]
            selected_ateliers = st.multiselect("Atelier", ateliers_options, ["All"])
            if "All" in selected_ateliers or len(selected_ateliers) == 0: selected_ateliers = ["All"]
        with col_f3:
            divisions_options = ["All", "SF1", "SF2"]
            selected_divisions = st.multiselect("Division", divisions_options, ["All"])
            if "All" in selected_divisions or len(selected_divisions) == 0: selected_divisions = ["All"]

        col_date = st.columns(1)[0]
        with col_date:
            min_date = df_ot_raw["Date de début planifiée"].min().to_pydatetime()
            max_date = df_ot_raw["Date de début planifiée"].max().to_pydatetime()
            date_range = st.date_input("📅 Filtre Date de début planifiée (Du - Au)", [min_date, max_date], key="date_range", format="DD/MM/YYYY")
            if len(date_range) == 2: start_date, end_date = pd.to_datetime(date_range[0]), pd.to_datetime(date_range[1])
            else: start_date, end_date = min_date, max_date

        def match_filters(poste):
            p = str(poste).upper()
            if "All" not in selected_ateliers:
                match_at = False
                if "Sulfurique (PS)" in selected_ateliers and "PS" in p: match_at = True
                if "Phosphorique (PP)" in selected_ateliers and "PP" in p: match_at = True
                if "Engrais (TSP/REX)" in selected_ateliers and ("TSP" in p or "REX" in p): match_at = True
                if "Feed (MCP/DCP)" in selected_ateliers and ("MCP" in p or "DCP" in p): match_at = True
                if not match_at: return False
            if "All" not in selected_divisions:
                match_div = False
                if "SF1" in selected_divisions and "SF1" in p: match_div = True
                if "SF2" in selected_divisions and "SF2" in p: match_div = True
                if not match_div: return False
            return True

        valid_postes = [p for p in all_postes_master_list if match_filters(p) and p in selected_postes]

        df = df_ot_raw[(df_ot_raw["Poste travail princ."].isin(valid_postes)) & (df_ot_raw["Date de début planifiée"].between(start_date, end_date)) & (~df_ot_raw["Poste travail princ."].astype(str).str.contains("cresseur", case=False, na=False))].copy()
        avis_df = avis_df_raw[(avis_df_raw["Poste travail princ."].isin(valid_postes)) & (~avis_df_raw["Poste travail princ."].astype(str).str.contains("cresseur", case=False, na=False))].copy()

        df = df[df["Poste travail princ."].astype(str).str.startswith(("SF1", "SF2"), na=False)].drop_duplicates()
        avis_df = avis_df[(avis_df["Ordre"].isna()) | (avis_df["Ordre"].astype(str).str.strip().eq(""))].drop_duplicates()

        if "Statut système" in df.columns: df["Statut OT"] = df["Statut système"].fillna("").astype(str).str.strip().str.split().str[0]
        st.success(f"OT après filtre : {len(df)} lignes | AVIS après filtre : {len(avis_df)} lignes")

        now = pd.Timestamp.now()
        results = calculate_all_kpis_and_intermediate_dfs(df, avis_df, now, valid_postes)
        calculated_kpis_df = results['calculated_kpis_df']
        df_processed = results['df_processed']

        cible = pd.DataFrame([{
            "TAUX_REALISATION_CORRECTIF/PT": 85, "OT préparation <1 mois": 80, "OT préparation >3 mois": 5, "OT préparation 1mois< <3mois": 15,
            "OT planification <1 mois": 80, "OT planification >3 mois": 5, "OT planification 1mois< <3mois": 15,
            "OT exécution <1 mois": 80, "OT exécution >3 mois": 5, "OT exécution 1mois< <3mois": 15,
            "appel avis approuvé": 95, "OT LANC ESTIME": 100, "Backlog préparation caractérisé": 100,
            "Backlog planification caractérisé": 100, "OT CONFIME": 100, "OT_COR_EGAL": 100,
        }], index=["CIBLE"])

        anomalies_ot_records = []
        anomalies_avis_records = []

        for poste in valid_postes:
            if poste not in df_processed["Poste travail princ."].values: continue
            df_poste = df_processed[df_processed["Poste travail princ."] == poste]
            avis_poste = results['avis_df_filtered'][results['avis_df_filtered']["Poste travail princ."] == poste]

            val_real = calculated_kpis_df.loc[poste, "TAUX_REALISATION_CORRECTIF/PT"] if poste in calculated_kpis_df.index else 100
            if pd.notna(val_real) and val_real < cible.loc['CIBLE', "TAUX_REALISATION_CORRECTIF/PT"]:
                count_anom = len(df_poste[(df_poste["Nº appel pl.entret."].fillna(0) == 0) & (~df_poste["Statut OT"].isin(["CLOT", "TCLO"]))])
                if count_anom > 0: anomalies_ot_records.append({"Poste travail princ.": poste, "KPI": "TAUX_REALISATION_CORRECTIF/PT", "Nb OT impactés": count_anom, "Action Suggérée": "Améliorer le taux de réalisation des OT."})

            val_prep_inf1 = calculated_kpis_df.loc[poste, "OT préparation <1 mois"] if poste in calculated_kpis_df.index else 100
            if pd.notna(val_prep_inf1) and val_prep_inf1 < cible.loc['CIBLE', "OT préparation <1 mois"]:
                count_anom = len(df_poste[(df_poste["Statut OT"] == "CRÉÉ") & (df_poste["Age préparation"] != "<1 mois")])
                if count_anom > 0: anomalies_ot_records.append({"Poste travail princ.": poste, "KPI": "OT préparation <1 mois", "Nb OT impactés": count_anom, "Action Suggérée": "Réduire l'âge de préparation des OT."})

            val_prep_sup3 = calculated_kpis_df.loc[poste, "OT préparation >3 mois"] if poste in calculated_kpis_df.index else 0
            if pd.notna(val_prep_sup3) and val_prep_sup3 > cible.loc['CIBLE', "OT préparation >3 mois"]:
                count_anom = len(df_poste[(df_poste["Statut OT"] == "CRÉÉ") & (df_poste["Age préparation"] == ">3 mois")])
                if count_anom > 0: anomalies_ot_records.append({"Poste travail princ.": poste, "KPI": "OT préparation >3 mois", "Nb OT impactés": count_anom, "Action Suggérée": "Traiter les OT ayant un âge de préparation > 3 mois."})

            val_planif_inf1 = calculated_kpis_df.loc[poste, "OT planification <1 mois"] if poste in calculated_kpis_df.index else 100
            if pd.notna(val_planif_inf1) and val_planif_inf1 < cible.loc['CIBLE', "OT planification <1 mois"]:
                count_anom = len(df_poste[(df_poste["Statut OT"] == "LANC") & (df_poste["Contient SOPL"] == 0) & (df_poste["Age planification"] != "<1 mois")])
                if count_anom > 0: anomalies_ot_records.append({"Poste travail princ.": poste, "KPI": "OT planification <1 mois", "Nb OT impactés": count_anom, "Action Suggérée": "Réduire l'âge de planification des OT."})

            val_planif_sup3 = calculated_kpis_df.loc[poste, "OT planification >3 mois"] if poste in calculated_kpis_df.index else 0
            if pd.notna(val_planif_sup3) and val_planif_sup3 > cible.loc['CIBLE', "OT planification >3 mois"]:
                count_anom = len(df_poste[(df_poste["Statut OT"] == "LANC") & (df_poste["Contient SOPL"] == 0) & (df_poste["Age planification"] == ">3 mois")])
                if count_anom > 0: anomalies_ot_records.append({"Poste travail princ.": poste, "KPI": "OT planification >3 mois", "Nb OT impactés": count_anom, "Action Suggérée": "Traiter les OT ayant un âge de planification > 3 mois."})

            val_exec_inf1 = calculated_kpis_df.loc[poste, "OT exécution <1 mois"] if poste in calculated_kpis_df.index else 100
            if pd.notna(val_exec_inf1) and val_exec_inf1 < cible.loc['CIBLE', "OT exécution <1 mois"]:
                count_anom = len(df_poste[(df_poste["Statut OT"] == "LANC") & (df_poste["Contient SOPL"] == 1) & (df_poste["Age exécution"] != "<1 mois")])
                if count_anom > 0: anomalies_ot_records.append({"Poste travail princ.": poste, "KPI": "OT exécution <1 mois", "Nb OT impactés": count_anom, "Action Suggérée": "Réduire l'âge d'exécution des OT."})

            val_exec_sup3 = calculated_kpis_df.loc[poste, "OT exécution >3 mois"] if poste in calculated_kpis_df.index else 0
            if pd.notna(val_exec_sup3) and val_exec_sup3 > cible.loc['CIBLE', "OT exécution >3 mois"]:
                count_anom = len(df_poste[(df_poste["Statut OT"] == "LANC") & (df_poste["Contient SOPL"] == 1) & (df_poste["Age exécution"] == ">3 mois")])
                if count_anom > 0: anomalies_ot_records.append({"Poste travail princ.": poste, "KPI": "OT exécution >3 mois", "Nb OT impactés": count_anom, "Action Suggérée": "Traiter les OT ayant un âge d'exécution > 3 mois."})

            for kpi_name, condition, action in [
                ("OT LANC ESTIME", (df_poste["Statut OT"] == "LANC") & (df_poste["OT LANC ESTIME"] == "NON"), "Estimer les coûts des OT lancés."),
                ("Backlog préparation caractérisé", (df_poste["Statut OT"] == "CRÉÉ") & (df_poste["Backlog préparation"] == "NON CARACTERISE"), "Caractériser le backlog de préparation."),
                ("Backlog planification caractérisé", (df_poste["Statut OT"] == "LANC") & (df_poste["Backlog planification"] == "NON CARACTERISE"), "Caractériser le backlog de planification."),
                ("OT CONFIME", df_poste["OT CONFIME"] == "NON", "Confirmer les OT terminés."),
                ("OT_COR_EGAL", df_poste["OT_COR_EGAL"] == "NON", "Rapprocher les coûts réels et budgétés.")
            ]:
                val_kpi = calculated_kpis_df.loc[poste, kpi_name] if poste in calculated_kpis_df.index else 100
                if pd.notna(val_kpi) and val_kpi < cible.loc['CIBLE', kpi_name]:
                    count_anom = len(df_poste[condition])
                    if count_anom > 0: anomalies_ot_records.append({"Poste travail princ.": poste, "KPI": kpi_name, "Nb OT impactés": count_anom, "Action Suggérée": action})

            val_avis = calculated_kpis_df.loc[poste, "appel avis approuvé"] if poste in calculated_kpis_df.index else 100
            if pd.notna(val_avis) and val_avis < cible.loc['CIBLE', "appel avis approuvé"]:
                count_avis_anom = len(avis_poste)
                if count_avis_anom > 0: anomalies_avis_records.append({"Poste travail princ.": poste, "KPI": "appel avis approuvé", "Nb Avis impactés": count_avis_anom, "Action Suggérée": "Créer un OT pour les avis sans ordre."})

        df_anomalies_ot = pd.DataFrame(anomalies_ot_records)
        df_anomalies_avis = pd.DataFrame(anomalies_avis_records)

        if not df_anomalies_ot.empty:
            pivot_ot = df_anomalies_ot.pivot_table(index="Poste travail princ.", columns="KPI", values="Nb OT impactés", aggfunc="sum", fill_value=0)
        else: pivot_ot = pd.DataFrame(columns=["Poste travail princ."])

        if not df_anomalies_avis.empty:
            pivot_avis = df_anomalies_avis.pivot_table(index="Poste travail princ.", columns="KPI", values="Nb Avis impactés", aggfunc="sum", fill_value=0)
            if "appel avis approuvé" in pivot_avis.columns: pivot_avis = pivot_avis.rename(columns={"appel avis approuvé": "Nb Avis sans ordre"})
        else: pivot_avis = pd.DataFrame(columns=["Poste travail princ."])

        anomalies_dashboard = pivot_ot.join(pivot_avis, how='outer').fillna(0).astype(int)
        if not anomalies_dashboard.empty:
            anomalies_dashboard["Total éléments impactés"] = anomalies_dashboard.sum(axis=1)
            total_row = pd.DataFrame(anomalies_dashboard.sum()).T; total_row.index = ["Total général"]
            anomalies_dashboard = pd.concat([anomalies_dashboard, total_row])
        else: anomalies_dashboard = pd.DataFrame()

        qty_kpis = ["TAUX_REALISATION_CORRECTIF/PT", "OT préparation <1 mois", "OT préparation >3 mois", "OT préparation 1mois< <3mois", "OT planification <1 mois", "OT planification >3 mois", "OT planification 1mois< <3mois", "OT exécution <1 mois", "OT exécution >3 mois", "OT exécution 1mois< <3mois"]
        qual_kpis = ["appel avis approuvé", "OT LANC ESTIME", "Backlog préparation caractérisé", "Backlog planification caractérisé", "OT CONFIME", "OT_COR_EGAL"]

        class_results = []
        for poste in calculated_kpis_df.index:
            row = calculated_kpis_df.loc[poste]
            s_qty = sum(get_kpi_score(k, row[k], cible.loc['CIBLE', k]) for k in qty_kpis if k in row.index)
            s_qual = sum(get_kpi_score(k, row[k], cible.loc['CIBLE', k]) for k in qual_kpis if k in row.index)
            p_qty = (s_qty / len(qty_kpis) * 100) if qty_kpis else 0
            p_qual = (s_qual / len(qual_kpis) * 100) if qual_kpis else 0
            class_results.append({
                "Poste travail princ.": poste,
                "Score KPIs Quantité": p_qty,
                "Score KPIs Qualité": p_qual,
                "Total performance ": (p_qty+p_qual)/2
            })
        df_class = pd.DataFrame(class_results)

        type_tableau = st.radio("Type de Tableau", ["Tableau de bord des KPIs", "Tableau de bord des Anomalies"], horizontal=True)

        if type_tableau == "Tableau de bord des KPIs":
            total_general_kpi = pd.DataFrame(calculated_kpis_df.mean()).T; total_general_kpi.index = ["Total général"]
            final_kpi = pd.concat([cible, calculated_kpis_df, total_general_kpi]).round(2)

            st.markdown('<div class="header-kpi">TABLEAU DE BORD DES KPIs</div>', unsafe_allow_html=True)
            st.table(final_kpi.style.apply(highlight_kpis, axis=1).format("{:.2f}"))

            st.markdown("---")
            st.subheader("Synthèse des Actions KPI par Poste de Travail")
            if not df_anomalies_ot.empty:
                display_actions = df_anomalies_ot.copy()
                if len(selected_postes) == len(all_postes_master_list) and "All" in selected_postes:
                    display_actions = display_actions[["KPI", "Nb OT impactés", "Action Suggérée"]]
                st.dataframe(display_actions, use_container_width=True)
            else: st.info("Tous les KPIs atteignent leurs cibles. Aucune action immédiate requise.")

            st.markdown("---")
            st.subheader("Classement des Postes de Travail par Qualité des KPIs")

            df_class_display = df_class.copy()
            df_class_display["Score KPIs Quantité"] = df_class_display["Score KPIs Quantité"].apply(lambda x: f"{x:.2f} %")
            df_class_display["Score KPIs Qualité"] = df_class_display["Score KPIs Qualité"].apply(lambda x: f"{x:.2f} %")
            df_class_display["Total performance "] = df_class_display["Total performance "].apply(lambda x: f"{x:.2f} %")

            total_gen_class = pd.DataFrame([{
                "Poste travail princ.": "Total général",
                "Score KPIs Quantité": f"{df_class['Score KPIs Quantité'].mean():.2f} %",
                "Score KPIs Qualité": f"{df_class['Score KPIs Qualité'].mean():.2f} %",
                "Total performance ": f"{df_class['Total performance '].mean():.2f} %"
            }])

            df_class_display = pd.concat([df_class_display, total_gen_class], ignore_index=True)
            st.table(df_class_display.style.apply(highlight_classification_table_kpis, axis=1))

            st.markdown("---")
            col_top1, col_top2, col_top3 = st.columns(3)
            with col_top1:
                st.markdown("#### Top 5 Quantité")
                top5 = df_class.nsmallest(5, "Score KPIs Quantité")[["Poste travail princ.", "Score KPIs Quantité"]]
                top5["Score KPIs Quantité"] = top5["Score KPIs Quantité"].round(2)
                st.dataframe(top5.set_index("Poste travail princ."))
            with col_top2:
                st.markdown("#### Top 5 Qualité")
                top5 = df_class.nsmallest(5, "Score KPIs Qualité")[["Poste travail princ.", "Score KPIs Qualité"]]
                top5["Score KPIs Qualité"] = top5["Score KPIs Qualité"].round(2)
                st.dataframe(top5.set_index("Poste travail princ."))
            with col_top3:
                st.markdown("#### Top 5 Performance Totale")
                top5 = df_class.nsmallest(5, "Total performance ")[["Poste travail princ.", "Total performance "]]
                top5["Total performance "] = top5["Total performance "].round(2)
                st.dataframe(top5.set_index("Poste travail princ."))

            st.markdown("---")
            df_class["Métier"] = df_class["Poste travail princ."].apply(get_groupe_metier)
            df_class["Atelier"] = df_class["Poste travail princ."].apply(get_groupe_atelier)
            df_class["Division"] = df_class["Poste travail princ."].apply(get_groupe_division)

            c1, c2, c3 = st.columns(3)

            with c1:
                df_m = df_class.groupby("Métier")["Total performance "].mean().reset_index()
                chart_m = alt.Chart(df_m).mark_bar(color='#3498db').encode(x='Métier:O', y='Total performance :Q')
                text_m = chart_m.mark_text(align='center', baseline='bottom', dy=-5).encode(text=alt.Text('Total performance :Q', format='.1f'))
                st.altair_chart((chart_m + text_m).configure_axisY(labels=False, ticks=False, grid=False, domain=False).configure_view(stroke='transparent').properties(height=250), use_container_width=True)

            with c2:
                df_a = df_class.groupby("Atelier")["Total performance "].mean().reset_index()
                chart_a = alt.Chart(df_a).mark_bar(color='#e74c3c').encode(x='Atelier:O', y='Total performance :Q')
                text_a = chart_a.mark_text(align='center', baseline='bottom', dy=-5).encode(text=alt.Text('Total performance :Q', format='.1f'))
                st.altair_chart((chart_a + text_a).configure_axisY(labels=False, ticks=False, grid=False, domain=False).configure_view(stroke='transparent').properties(height=250), use_container_width=True)

            with c3:
                df_d = df_class.groupby("Division")["Total performance "].mean().reset_index()
                chart_d = alt.Chart(df_d).mark_bar(color='#2ecc71').encode(x='Division:O', y='Total performance :Q')
                text_d = chart_d.mark_text(align='center', baseline='bottom', dy=-5).encode(text=alt.Text('Total performance :Q', format='.1f'))
                st.altair_chart((chart_d + text_d).configure_axisY(labels=False, ticks=False, grid=False, domain=False).configure_view(stroke='transparent').properties(height=250), use_container_width=True)

        else:
            st.markdown('<div class="header-anomalie">TABLEAU DE BORD DES ANOMALIES</div>', unsafe_allow_html=True)
            if not anomalies_dashboard.empty: st.dataframe(anomalies_dashboard, use_container_width=True)
            else: st.info("Aucune anomalie détectée.")

        st.markdown("---")
        st.subheader("Exporter les plans d'action détaillés")
        postes_avec_anomalies = anomalies_dashboard[anomalies_dashboard.index != "Total général"].index.tolist()

        if postes_avec_anomalies:
            selected_poste_export = st.selectbox("Sélectionnez le poste de travail pour générer le fichier Excel :", options=postes_avec_anomalies)

            if st.button("📥 Générer et télécharger le fichier Excel", type="primary"):
                with st.spinner("Génération du fichier en cours..."):
                    output = io.BytesIO()
                    with pd.ExcelWriter(output, engine='xlsxwriter') as writer:
                        kpis_en_defaut = df_anomalies_ot[df_anomalies_ot["Poste travail princ."] == selected_poste_export]["KPI"].unique().tolist()
                        if "appel avis approuvé" in pivot_avis.columns and selected_poste_export in pivot_avis.index and pivot_avis.loc[selected_poste_export, "Nb Avis sans ordre"] > 0:
                            kpis_en_defaut.append("appel avis approuvé")

                        for kpi in kpis_en_defaut:
                            sheet_data = pd.DataFrame()

                            if kpi != "appel avis approuvé":
                                df_poste_filtered = df_processed[df_processed["Poste travail princ."] == selected_poste_export].copy()
                                if kpi == "TAUX_REALISATION_CORRECTIF/PT": subset_ot = df_poste_filtered[(df_poste_filtered["Nº appel pl.entret."].fillna(0) == 0) & (~df_poste_filtered["Statut OT"].isin(["CLOT", "TCLO"]))]
                                elif kpi == "OT préparation <1 mois": subset_ot = df_poste_filtered[(df_poste_filtered["Statut OT"] == "CRÉÉ") & (df_poste_filtered["Age préparation"] != "<1 mois")]
                                elif kpi == "OT préparation >3 mois": subset_ot = df_poste_filtered[(df_poste_filtered["Statut OT"] == "CRÉÉ") & (df_poste_filtered["Age préparation"] == ">3 mois")]
                                elif kpi == "OT planification <1 mois": subset_ot = df_poste_filtered[(df_poste_filtered["Statut OT"] == "LANC") & (df_poste_filtered["Contient SOPL"] == 0) & (df_poste_filtered["Age planification"] != "<1 mois")]
                                elif kpi == "OT planification >3 mois": subset_ot = df_poste_filtered[(df_poste_filtered["Statut OT"] == "LANC") & (df_poste_filtered["Contient SOPL"] == 0) & (df_poste_filtered["Age planification"] == ">3 mois")]
                                elif kpi == "OT exécution <1 mois": subset_ot = df_poste_filtered[(df_poste_filtered["Statut OT"] == "LANC") & (df_poste_filtered["Contient SOPL"] == 1) & (df_poste_filtered["Age exécution"] != "<1 mois")]
                                elif kpi == "OT exécution >3 mois": subset_ot = df_poste_filtered[(df_poste_filtered["Statut OT"] == "LANC") & (df_poste_filtered["Contient SOPL"] == 1) & (df_poste_filtered["Age exécution"] == ">3 mois")]
                                elif kpi == "OT LANC ESTIME": subset_ot = df_poste_filtered[(df_poste_filtered["Statut OT"] == "LANC") & (df_poste_filtered["OT LANC ESTIME"] == "NON")]
                                elif kpi == "Backlog préparation caractérisé": subset_ot = df_poste_filtered[(df_poste_filtered["Statut OT"] == "CRÉÉ") & (df_poste_filtered["Backlog préparation"] == "NON CARACTERISE")]
                                elif kpi == "Backlog planification caractérisé": subset_ot = df_poste_filtered[(df_poste_filtered["Statut OT"] == "LANC") & (df_poste_filtered["Backlog planification"] == "NON CARACTERISE")]
                                elif kpi == "OT CONFIME": subset_ot = df_poste_filtered[df_poste_filtered["OT CONFIME"] == "NON"]
                                elif kpi == "OT_COR_EGAL": subset_ot = df_poste_filtered[df_poste_filtered["OT_COR_EGAL"] == "NON"]
                                else: subset_ot = pd.DataFrame()

                                if not subset_ot.empty:
                                    old_cols = ["Ordre", "Désignation", "Emplacement technique", "Poste travail princ.", "Statut système", "Statut utilisateur", "Date de début planifiée", "Type d'ordre", "Backlog préparation", "Backlog planification"]
                                    new_cols = ["Ordre de travail", "Désignation", "Poste technique", "Poste de travail principal", "Statut système", "Statut utilisateur", "Date de début planifiée", "Type d'ordre", "Caractérisation backlog Préparation", "Caractérisation backlog Planification"]
                                    subset_ot = rename_safe(subset_ot, old_cols, new_cols)
                                    subset_ot["KPI impacté"] = kpi
                                    subset_ot["Action recommandée"] = f"Corriger l'indicateur {kpi}."
                                    sheet_data = pd.concat([sheet_data, subset_ot])

                            if kpi == "appel avis approuvé":
                                subset_avis = results['avis_df_filtered'][results['avis_df_filtered']["Poste travail princ."] == selected_poste_export].copy()
                                if not subset_avis.empty:
                                    old_cols_avis = ["Avis", "Désignation texte", "Emplacement technique", "Poste travail princ.", "Statut utilisateur", "Créé le"]
                                    new_cols_avis = ["Avis", "Désignation", "Poste technique", "Poste de travail principal", "Statut", "Date de création"]
                                    subset_avis = rename_safe(subset_avis, old_cols_avis, new_cols_avis)
                                    subset_avis["KPI impacté"] = kpi
                                    subset_avis["Action recommandée"] = "Créer un Ordre de Travail pour cet Avis ou clarifier son statut."
                                    sheet_data = pd.concat([sheet_data, subset_avis])

                            if not sheet_data.empty:
                                sheet_name = kpi.replace("/", "_").replace(" ", "_")[:31]
                                sheet_data.to_excel(writer, sheet_name=sheet_name, index=False)

                    output.seek(0)
                    st.download_button(
                        label="✅ Cliquez ici pour télécharger le fichier",
                        data=output.getvalue(),
                        file_name=f"Plan_Action_{selected_poste_export.replace(' ', '_')}.xlsx",
                        mime="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
                    )
        else:
            st.info("Aucune anomalie n'a été détectée. L'export est désactivé.")

    except Exception as e:
        st.error(f"Une erreur est survenue lors du traitement des fichiers : {e}")



